# Generated by Codex for dashboard user table
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DashboardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone_celular', models.CharField(max_length=20)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('position_id', models.IntegerField(blank=True, null=True)),
                ('unidade_id', models.IntegerField(blank=True, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('situacao_id', models.IntegerField(blank=True, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
