# Generated by Django 4.2.23 on 2025-07-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sample_prp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPermission',
        ),
        migrations.DeleteModel(
            name='DashboardUser',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
